server:
  port: 8808
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search-engine?serverTimezone=GMT
    username: root
    password: yhlo
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    max-active: 3
  aop:
    proxy-target-class=true:1
  data:
    elasticsearch:
